# inherit_from:
#   - ../.rubocop.yml
#   - ../.rubocop_todo.yml

require: rubocop-rspec

Style/Encoding:
  Enabled: false

Style/LineLength:
  Max: 120

Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Exclude:
    - bin/**

