# inherit_from:
#   - ../.rubocop.yml
#   - ../.rubocop_todo.yml

require: rubocop-rspec

AllCops:
  RunRailsCops: true
  Exclude:
    - bin/**
    - db/schema.rb

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/DescribeClass:
  Exclude:
    - spec/views/**/*

RSpec/FilePath:
  Exclude:
    - spec/routing/**/*

