# inherit_from:
#   - ../.rubocop.yml
#   - ../.rubocop_todo.yml

require: rubocop-rspec

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/DescribeClass:
  Exclude:
    - spec/views/**/*

Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Exclude:
    - bin/**
